### ISSUE TITLE
sd image build ends without creating the image

### ISSUE THREAD

**Issue by julianctrt** [kit-ipq/ZCU208#1]
hello,

when running the make command in the sdbuild folder of PYNQ cloned repository with the board path after downloaded the bsp to the folder of this cloned repo the make start to check the environment but after check all the dependencies it ends without any error.

I've done the setup_env.sh previously as the pynq documentation  describe without problem.

also the settings for vivado and petalinux was previously run in the same terminal and the webtalk off.

The thing is the make command works and start to generate the image for the boards in the board folder but I don't want to go in this direction since it takes a lot of time and I'm not sure if I put the zcu208 folder inside it will generate.

any thoughts?

thanks

**Comment by Yamakaja** [comment]
Hey, is this still an issue? You've provided me with rather little to go on, so is there anything else you could share? Log files for example? Which commands did you invoke? What exactly are you observing, and what did you expect to see?

**Comment by julianctrt** [comment]
hi @Yamakaja, thanks for reply. 

Since pynq 3.0 officially support the zcu208 this is not needed for me so I didn't try to solve it. but my guess is some package is missing in my setup or something like that and exit without error. 

Thanks anyway.
